# Generated by Django 4.2.24 on 2025-11-04 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_paymenthistory_adjustments_total_amt_and_more'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='primary_payment_record',
            field=models.ForeignKey(blank=True, help_text='Links this booking to its primary payment record for refunds or adjustments.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_bookings_direct', to='billing.paymenthistory'),
        ),
    ]
