# Generated by Django 4.2.24 on 2025-10-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='address_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Stored as PRE-TAX price per 2-hour service block.', max_digits=8),
        ),
    ]
