# Generated by Django 4.2.24 on 2026-03-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_booking_primary_payment_record'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jobassignment',
            index=models.Index(fields=['employee'], name='scheduling__employe_a488b8_idx'),
        ),
        migrations.AddIndex(
            model_name='jobassignment',
            index=models.Index(fields=['booking'], name='scheduling__booking_429978_idx'),
        ),
    ]
