# Generated by Django 4.2.24 on 2025-10-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_cart_address_key_alter_cartitem_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='address_key',
            field=models.CharField(blank=True, help_text='Normalized address string for session-level cart isolation.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, help_text='Anonymous session identifier for guests.', max_length=40, null=True),
        ),
    ]
