# Generated by Django 4.2.24 on 2025-10-22 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_alter_cart_address_key_alter_cart_session_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='service_category',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='time_slot',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
