# Generated by Django 4.2.24 on 2025-10-28 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payments',
        ),
    ]
