# Generated by Django 4.2.24 on 2025-11-03 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='Anonymous session identifier for guests.', max_length=40, null=True)),
                ('address_key', models.CharField(blank=True, db_index=True, help_text='Normalized address string for session-level cart isolation.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjustments_total_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('service_address', models.TextField(blank=True)),
                ('stripe_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded'), ('Adjustment', 'Adjustment')], default='Paid', max_length=20)),
                ('payment_type', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_payment_record', to='scheduling.booking')),
                ('linked_bookings', models.ManyToManyField(blank=True, related_name='linked_payment_records', to='scheduling.booking')),
                ('parent', models.ForeignKey(blank=True, help_text='Links follow-up payment records (refunds, add-ons, etc.) back to the root payment.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='billing.paymenthistory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Amount in cents')),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('stripe_payment_intent_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('requires_payment_method', 'Requires Payment Method'), ('requires_confirmation', 'Requires Confirmation'), ('requires_action', 'Requires Action'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('canceled', 'Canceled')], default='processing', max_length=32)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('receipt_url', models.URLField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_address', models.CharField(default='Unknown', help_text='Full street address where this service is performed.', max_length=255)),
                ('date', models.DateField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Stored as PRE-TAX price per 2-hour service block.', max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.cart')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduling.employee')),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduling.servicecategory')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduling.timeslot')),
            ],
            options={
                'unique_together': {('cart', 'service_category', 'time_slot', 'date', 'employee')},
            },
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['session_key'], name='billing_car_session_352cf0_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user'], name='billing_car_user_id_09cf1e_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['address_key'], name='billing_car_address_b1138d_idx'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('user', 'session_key', 'address_key'), name='unique_user_session_address_cart'),
        ),
    ]
