# Generated by Django 4.2.24 on 2025-10-22 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_alter_cartitem_unique_together_remove_cartitem_cart_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='Anonymous session identifier for guests.', max_length=40, null=True)),
                ('address_key', models.CharField(blank=True, db_index=True, help_text='Normalized address string for session-level cart isolation.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Stored as PRE-TAX price per 2-hour service block.', max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.cart')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduling.employee')),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduling.servicecategory')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduling.timeslot')),
            ],
            options={
                'unique_together': {('cart', 'service_category', 'time_slot', 'date', 'employee')},
            },
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['session_key'], name='billing_car_session_352cf0_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user'], name='billing_car_user_id_09cf1e_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['address_key'], name='billing_car_address_b1138d_idx'),
        ),
    ]
