# Generated by Django 4.2.24 on 2025-11-04 17:21

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
        ('billing', '0002_auto_20251103_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='adjustments_total_amt',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='All payment records associated with this booking.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_payment_records', to='scheduling.booking'),
        ),
    ]
