# Generated by Django 4.2.24 on 2025-10-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_cart_cartitem_cart_billing_car_session_352cf0_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('user', 'session_key', 'address_key'), name='unique_user_session_address_cart'),
        ),
    ]
