# Generated by Django 4.2.24 on 2025-11-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_paymenthistory_adjustments_total_amt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='stripe_payment_id',
            field=models.CharField(blank=True, help_text='Unique Stripe payment intent ID for this transaction.', max_length=255, null=True, unique=True),
        ),
    ]
