# Generated by Django 4.2.24 on 2026-03-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_paymenthistory_stripe_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
