# Generated by Django 4.2.24 on 2025-10-28 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0004_paymenthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='cart',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='payment_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')], default='Paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='service_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='stripe_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
