# Generated by Django 4.2.24 on 2025-10-28 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_alter_cartitem_unique_together_remove_cartitem_cart_and_more'),
        ('billing', '0005_remove_paymenthistory_cart_paymenthistory_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='scheduling.booking'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded'), ('Adjustment', 'Adjustment')], default='Paid', max_length=20),
        ),
    ]
