# Generated by Django 4.2.24 on 2025-10-29 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0007_remove_booking_payments'),
        ('billing', '0008_alter_paymenthistory_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent payment record this refund or adjustment relates to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='billing.paymenthistory'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_records', to='scheduling.booking'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
