# Generated by Django 4.2.24 on 2025-10-29 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_paymenthistory_parent_alter_paymenthistory_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='billing.paymenthistory'),
        ),
    ]
