# Generated by Django 4.2.24 on 2025-10-30 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_remove_booking_payments'),
        ('billing', '0010_alter_paymenthistory_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='linked_bookings',
            field=models.ManyToManyField(blank=True, related_name='linked_payment_records', to='scheduling.booking'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_payment_record', to='scheduling.booking'),
        ),
    ]
