# Generated by Django 4.2.24 on 2025-10-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_paymenthistory_linked_bookings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='service_address',
            field=models.CharField(default='Unknown', help_text='Full street address where this service is performed.', max_length=255),
        ),
    ]
