# Generated by Django 4.2.24 on 2025-11-05 01:25

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_send_on', models.DateField(default=core.models.first_day_next_month)),
                ('unsubscribed', models.BooleanField(default=False)),
                ('token', models.CharField(editable=False, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_sub', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['next_send_on'], name='core_newsle_next_se_e631f9_idx'), models.Index(fields=['unsubscribed'], name='core_newsle_unsubsc_170920_idx')],
            },
        ),
    ]
