# Generated by Django 4.2.24 on 2025-11-03 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('preferred_contact', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], default='email', max_length=16)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('billing_street_address', models.CharField(blank=True, max_length=255)),
                ('billing_city', models.CharField(blank=True, max_length=100)),
                ('billing_state', models.CharField(blank=True, max_length=100)),
                ('billing_zipcode', models.CharField(blank=True, max_length=20)),
                ('region', models.CharField(blank=True, help_text='Country/region code (e.g., US, DE).', max_length=2)),
                ('service_street_address', models.CharField(blank=True, max_length=255)),
                ('service_city', models.CharField(blank=True, max_length=100)),
                ('service_state', models.CharField(blank=True, max_length=100)),
                ('service_zipcode', models.CharField(blank=True, max_length=20)),
                ('service_region', models.CharField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': 'Customer Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
