# Generated by Django 4.2.24 on 2025-10-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registeredcustomer',
            options={},
        ),
        migrations.RemoveField(
            model_name='registeredcustomer',
            name='created_at',
        ),
        migrations.AddField(
            model_name='registeredcustomer',
            name='region',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='registeredcustomer',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registeredcustomer',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registeredcustomer',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registeredcustomer',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='registeredcustomer',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registeredcustomer',
            name='street_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registeredcustomer',
            name='unique_customer_id',
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterField(
            model_name='registeredcustomer',
            name='zipcode',
            field=models.CharField(max_length=20),
        ),
    ]
