# Generated by Django 4.2.24 on 2026-04-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
