# Generated by Django 4.2.24 on 2025-10-15 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0002_alter_registeredcustomer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registeredcustomer',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Registered Customer', 'verbose_name_plural': 'Registered Customers'},
        ),
        migrations.AddField(
            model_name='registeredcustomer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredcustomer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='registeredcustomer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered_customer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registeredcustomer',
            name='unique_customer_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
