# Generated by Django 4.2.24 on 2025-10-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_registeredcustomer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredcustomer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='registeredcustomer',
            name='state',
        ),
        migrations.RemoveField(
            model_name='registeredcustomer',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='registeredcustomer',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='registeredcustomer',
            name='billing_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registeredcustomer',
            name='billing_state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='registeredcustomer',
            name='billing_street_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='registeredcustomer',
            name='billing_zipcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='registeredcustomer',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
